# Generated by Django 3.1.1 on 2020-09-29 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='voter',
            field=models.ManyToManyField(related_name='voter_total', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoteBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('voter', models.ManyToManyField(related_name='voter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
