# Generated by Django 3.1.1 on 2020-09-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200930_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteboard',
            name='boardid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_connect', to='board.board'),
        ),
    ]
