# Generated by Django 3.1.1 on 2020-09-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200930_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='body',
        ),
    ]
