# Generated by Django 3.1.1 on 2020-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_board_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
